#!/usr/bin/env bash

set -euxo pipefail

BRANCH=$1
CHAIN=$2
DOMAIN=$3

if [[ ! -d arb ]]; then
  git clone https://github.com/tyjvazum/arb.git
fi

cd arb

git fetch origin
git checkout -B $BRANCH
git reset --hard origin/$BRANCH
./deploy/setup $CHAIN $DOMAIN
