#!/usr/bin/env bash

set -euxo pipefail

CHAIN=$1
DOMAIN=$2

touch ~/.hushlogin

sed -i -E 's/#?PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config

mkdir -p \
  /etc/systemd/system/bitcoind.service.d \
  /etc/systemd/system/arb.service.d

printf "[Service]\nEnvironment=CHAIN=%s\n" $CHAIN \
  | tee /etc/systemd/system/bitcoind.service.d/override.conf \
  > /etc/systemd/system/arb.service.d/override.conf

hostnamectl set-hostname $DOMAIN

apt-get install --yes \
  acl \
  clang \
  libsqlite3-dev\
  libssl-dev \
  pkg-config \
  ufw \
  vim

ufw default allow outgoing
ufw default deny incoming

ufw allow 8080
ufw allow http
ufw allow https
ufw allow ssh

case $CHAIN in
  main)
    ufw allow 8333
    ;;
  signet)
    ufw allow 38333
    ;;
  test)
    ufw allow 18333
    ;;
  *)
    echo "Unknown chain: $CHAIN"
    exit 1
    ;;
esac

ufw --force enable

if ! which bitcoind; then
  ./bin/install-bitcoin-core-linux
fi

bitcoind --version

if [[ ! -e ~/.cargo/env ]]; then
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
fi

source ~/.cargo/env

rustup update stable

cargo build --release
if [[ -f /usr/local/bin/arb ]]; then
  mv /usr/local/bin/arb /usr/local/bin/arb.bak
fi
cp target/release/arb /usr/local/bin/arb

id --user bitcoin || useradd --system bitcoin
id --user arb || useradd --system arb

cp deploy/bitcoind.service /etc/systemd/system/
mkdir -p /etc/bitcoin
cp deploy/bitcoin.conf /etc/bitcoin/bitcoin.conf
systemctl daemon-reload
systemctl enable bitcoind
systemctl restart bitcoind

case $CHAIN in
  main)
    COOKIE_FILE_DIR=/var/lib/bitcoind
    ;;
  signet)
    COOKIE_FILE_DIR=/var/lib/bitcoind/signet
    ;;
  test)
    COOKIE_FILE_DIR=/var/lib/bitcoind/testnet3
    ;;
  *)
    echo "Unknown chain: $CHAIN"
    exit 1
    ;;
esac

while [[ ! -f $COOKIE_FILE_DIR/.cookie ]]; do
  echo "Waiting for bitcoind…"
  sleep 1
done

setfacl -m arb:x /var/lib/bitcoind
setfacl -m arb:x $COOKIE_FILE_DIR
setfacl -dm arb:r $COOKIE_FILE_DIR
setfacl -m arb:r $COOKIE_FILE_DIR/.cookie

cp deploy/arb.service /etc/systemd/system/
systemctl daemon-reload
systemctl enable arb
systemctl restart arb

while ! curl --fail https://$DOMAIN/status; do
  echo "Waiting for arb at https://$DOMAIN/status…"
  sleep 1
done
